#######################################################################
#
#   Makefile for the taylor translator
#		

all:   
	(cd src; make taylor; mv taylor ../;)


clean:
	cd src; make clean;
	cd test; make clean;
	cd gtest; make clean
	cd dtest; make clean;
	cd qtest; make clean;
#######################################################################
