#include "taylor.h"

/***********************************************************************
 *
 * Code generated by the TAYLOR translator.
 */

main(int argc, char **argv)
{
	 int       i, j, order=20, itmp=0, direction = 1, nsteps = -1;
	 double    ftmp, dstep, tolerance, rtolerance, log10tolerance, log10rtolerance;
	 MY_FLOAT  startT, stopT, nextT;
	 MY_FLOAT  myFloatZero;
	 MY_FLOAT  xx[13], yy[13], zz[13];
	 MY_FLOAT  **jet;
	 InitMyFloat(myFloatZero);
	 InitMyFloat(startT);
	 InitMyFloat(stopT);
	 InitMyFloat(nextT);
	 for(i=0; i<13; i++){InitMyFloat(xx[i]); InitMyFloat(yy[i]);InitMyFloat(zz[i]);}

	 MakeMyFloatA(myFloatZero, 0);

	 /* assign initials */
	 MakeMyFloatC(xx[0],"-1289359.131", (double)-1289359.131);
	 MakeMyFloatC(xx[1],"435580.8098", (double)435580.8098);
	 MakeMyFloatC(xx[2],"217346.3392", (double)217346.3392);
	 MakeMyFloatC(xx[3],"-56393719.99", (double)-56393719.99);
	 MakeMyFloatC(xx[4],"125599283.6", (double)125599283.6);
	 MakeMyFloatC(xx[5],"54475540.72", (double)54475540.72);
	 MakeMyFloatC(xx[6],"-0.005589", (double)-0.005589);
	 MakeMyFloatC(xx[7],"-0.013552", (double)-0.013552);
	 MakeMyFloatC(xx[8],"-0.005606", (double)-0.005606);
	 MakeMyFloatC(xx[9],"-28.101464", (double)-28.101464);
	 MakeMyFloatC(xx[10],"-10.359519", (double)-10.359519);
	 MakeMyFloatC(xx[11],"-4.491546", (double)-4.491546);
	 MakeMyFloatC(stopT, "10000", (double)(10000));
	 MakeMyFloatC(startT, "0", (double)(0));
	 MakeMyFloatC(nextT, "100", (double)(100) );
	 dstep = (double)100;
	 fprintf(stderr,"Enter absolute error tolerance: "); 
	 scanf("%le", &tolerance);
	 fprintf(stderr,"Enter relative error tolerance: "); 
	 scanf("%le", &rtolerance);
	 log10tolerance  = log10(tolerance);
	 log10rtolerance = log10(rtolerance);

	 /* the main loop */

	 if(dstep < (double)0.0) { direction = -1;}
	 do  {
		 printf("%g %g %g %g %g %g %g %g %g %g %g %g %g\n",(double)xx[0],(double)xx[1],(double)xx[2],(double)xx[3],(double)xx[4],(double)xx[5],(double)xx[6],(double)xx[7],(double)xx[8],(double)xx[9],(double)xx[10],(double)xx[11],(double)startT);

		 itmp = taylor_step_nbp( &startT, xx, direction, 1, log10tolerance, log10rtolerance, &stopT, &nextT, &order);
	     } while(itmp == 0); /* while */ 
	 exit(0); 
 } 
